name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the branch name
        id: branch
        run: echo ::set-output name=branch::${{ github.ref }}

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /var/www/153.92.5.231/dev-jobvacancies-api 
            git stash
            git checkout main
            git pull origin main
